### PR TITLE
Revised IRefWeb ice-to-bio rules

### PR DESCRIPTION
**Pull request by bill-baumgartner**
This pull request consists of changes related to improvements/updates in the IRefWeb ice-to-bio rules. The rules now include distinct rules covering the three types of interactions cataloged by IRefWeb: 1) intra-molecular, 2) binary, and 3) n-ary. I'd be happy to go over the changes with you. Please let me know if you have any questions.

### CODE REVIEW

**Comment by sinistral** [comment]
Looks good to me, but I'd like for Elizabeth to weigh in on the rules before merging.

**Comment by ekwhite** [comment]
Thanks, Bill.  This is a lot of work.  Let me look it over by end of day.  I think it's probably all perfect but I could learn something by reading more closely.

**Comment by ekwhite** [comment]
This is all good; did I not merge correctly before?

**Comment by ekwhite** [comment]
Did I not merge this correctly?

**Comment by ekwhite** [comment]
ok.  I think it's in now.

**Pull request merged**
